### ISSUE TITLE
Grav 0.9.16 error

### ISSUE THREAD

**Issue by hexplor** [nunopress/grav-plugin-simple_form#7]
Access level to Grav\Plugin\Simple_FormPlugin::mergeConfig() must be protected (as in class Grav\Common\Plugin) or weaker

According to grav creator: "its because we now have a mergeConfig() in the base plugin class
and simple_form got one named the same"

**Comment by namaless** [comment]
Thanks!!
Fixed: https://github.com/nunopress/grav-plugin-simple_form/releases/tag/v1.2.4
