### ISSUE TITLE
Not working with Grav's Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [nunopress/grav-plugin-simple_form#8]
The plugin Simple Form can't be configured using the new [Grav's Admin Panel](https://github.com/getgrav/grav-plugin-admin). For example, if we go to the settings page of the plugin (url `/admin/plugins/simple_form`) and click on *Save*, there's the following error:

> **Validation failed:** fields is not defined in blueprints

According to a Grav developer: "These plugins just need to get updated with appropriate blueprint files so they will work in the admin plugin."

My config: Grav v0.9.39, Admin Panel v0.4.2, Simple Form v1.2.6

**Comment by tramber91** [comment]
Same issue for me
My config: Grav v0.9.40, Admin Panel v0.4.3, Simple Form v1.2.6

**Comment by tramber91** [comment]
Hi
can you have a look here
http://grav.en-toutes-lettres.fr/location
I don't know why but all new fields I can add come after the Submit button ??

I use default template

<i>My form in md file</i>

<code>
fields:
      name:
        type: "text"
        title: "Nom"
        default: ""
        placeholder: "Nom"
        class: ""
        required: true
      email:
        type: "email"
        title: "Email"
        default: ""
        placeholder: "E-mail"
        class: ""
        required: true
      phone:
        type: "text"
        title: "Téléphone"
        default: ""
        placeholder: "Téléphone"
        class: ""
        required: false
      message:
        type: "textarea"
        title: "Message"
        default: ""
        placeholder: "Message"
        class: ""
        required: true
      submit:
        type: "submit"
        title: "Envoyer"
        default: ""
        class: "btn-link btn-link2"
  messages:
      success: "Votre message a été envoyé. Merci."
</code>
My config: Grav v0.9.40, Admin Panel v0.4.3, Simple Form v1.2.6

Thanks

**Comment by namaless** [comment]
Sorry for delay, the plugin is updated (tomorrow release new update for the admin plugin integration). Please read the readme before update because the plugin change how to working (removed the fields from header) so you need to update the template (add twig function) and the fields need to put in template with html code.

**Comment by namaless** [comment]
Ok I update simple_form for working fine with admin plugin.
