### ISSUE TITLE
No more token in admin panel ?

### ISSUE THREAD

**Issue by tramber91** [nunopress/grav-plugin-simple_form#9]
Hi
I just update the pluging
No more configuration area including token in admin panel of the plugin
My form also deseapear of  my page  (test site)
Bertrand

**Comment by namaless** [comment]
Hello, following the readme you need first to add the Twig function into your template or you can put into the page but remember to activate the twig process into this page.
`{{ simple_form() }}`

After this into the page options you can found the new plugin block, you enter token, select the template and select the redirect_to page (the page displayed after the form sended).

The page template see the list of templates foundit into theme-dir/templates/plugins/simple_form/ folder so if you have a personal form you need to put in this location. Or if you use the standard form (with name, email, message) you can select the default template you see into the list.

I leave the issue open if you need more informations ^^

**Comment by tramber91** [comment]
Hi
1) Ok I've got my standard form on my page :=)

2) previously I did some test with special template coming from theme Photographer
http://demo.getgrav.org/photographer-skeleton/location
seems not working as it was set

3)  you said
The page template see the list of templates foundit 'into theme-dir/templates/plugins/simple_form/'

**Comment by tramber91** [comment]
oops, i'm not specialisy of Markdown
3) i can see these templates only if they are on main plugin folder :+1:
/grav/user/plugins/simple_form/templates/plugins/simple_form

**Comment by namaless** [comment]
This not working because the theme template not updated. Tomorrow Ill try to send a pull request for update the theme based on the latest version of our plugin :)

**Comment by namaless** [comment]
Ok foundit the bug, tomorrow release the new updated version for the plugin and working to the theme for update with the new version of our plugin.

**Comment by namaless** [comment]
Ok, I release a new version for simple_form (fixed the template selection issue) and sended pull request to skeleton and theme. You can waiting the new version of the theme or check my pull request and update your site :)
